#!/usr/bin/env bash
# Local /model command demo harness — isolated KittyPaw home so the user's
# real ~/.kittypaw/ daemon, secrets, and chat history are untouched.
#
# Subcommands:
#   setup   — create $TEST_HOME with config.toml registering 4 free models.
#             Idempotent: existing files are NOT overwritten unless --force.
#   server  — start an isolated daemon on $TEST_PORT (default :3001),
#             logging to /tmp/kittypaw-dev-models.log.
#   chat    — attach the chat REPL to the isolated daemon.
#   stop    — stop the isolated daemon.
#   clean   — remove $TEST_HOME entirely (user-initiated, never automatic).
#   status  — print the current isolation state.
#
# Vendor keys come from the environment — never embedded here, never logged.
# The script refuses to start the daemon if no key is exported (silent
# failure on the first chat turn would be a worse UX).

set -euo pipefail

TEST_HOME="${KITTYPAW_DEV_HOME:-/tmp/kittypaw-dev-models}"
TEST_PORT="${KITTYPAW_DEV_PORT:-3001}"
LOG_FILE="${KITTYPAW_DEV_LOG:-/tmp/kittypaw-dev-models.log}"

# bin/kittypaw is a sibling of this script's apps/kittypaw root.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
KP_BIN="$APP_ROOT/bin/kittypaw"

cmd="${1:-help}"
shift || true

ensure_binary() {
  if [[ ! -x "$KP_BIN" ]]; then
    echo "bin/kittypaw not built. run: make build" >&2
    exit 1
  fi
}

write_config_if_missing() {
  local force="${1:-no}"
  local cfg="$TEST_HOME/accounts/default/config.toml"
  if [[ -f "$cfg" && "$force" != "force" ]]; then
    echo "config exists: $cfg (use --force to overwrite)"
    return
  fi
  mkdir -p "$TEST_HOME/accounts/default"
  cat > "$cfg" <<'TOML'
# Generated by scripts/dev-models.sh setup. Edit freely — re-run `setup
# --force` to regenerate from the template.

[llm]
default = "groq-qwen"

[[llm.models]]
id = "groq-qwen"
provider = "groq"
model = "qwen/qwen3-32b"
max_tokens = 1024

[[llm.models]]
id = "groq-llama"
provider = "groq"
model = "llama-3.3-70b-versatile"
max_tokens = 1024

[[llm.models]]
id = "mistral-medium"
provider = "mistral"
model = "mistral-medium-latest"
max_tokens = 1024

[[llm.models]]
id = "ministral-8b"
provider = "mistral"
model = "ministral-8b-latest"
max_tokens = 1024
TOML
  touch "$TEST_HOME/server.toml"
  echo "wrote $cfg (4 models — groq-qwen / groq-llama / mistral-medium / ministral-8b)"
}

require_keys() {
  local missing=()
  if [[ -z "${GROQ_API_KEY:-}" ]]; then missing+=("GROQ_API_KEY"); fi
  if [[ -z "${MISTRAL_API_KEY:-}" ]]; then missing+=("MISTRAL_API_KEY"); fi
  if (( ${#missing[@]} > 0 )); then
    echo "missing env: ${missing[*]}" >&2
    echo "  Groq:    https://console.groq.com/keys" >&2
    echo "  Mistral: https://console.mistral.ai/api-keys (Experiment plan, no card)" >&2
    return 1
  fi
}

case "$cmd" in
setup)
  force="no"
  if [[ "${1:-}" == "--force" ]]; then force="force"; fi
  write_config_if_missing "$force"
  echo "TEST_HOME=$TEST_HOME"
  ;;

server)
  ensure_binary
  require_keys
  if [[ ! -f "$TEST_HOME/accounts/default/config.toml" ]]; then
    write_config_if_missing
  fi
  if lsof -nP -iTCP:"$TEST_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "port :$TEST_PORT already in use — stop the existing daemon first or set KITTYPAW_DEV_PORT" >&2
    exit 1
  fi
  echo "starting daemon on :$TEST_PORT (HOME=$TEST_HOME, log=$LOG_FILE)"
  HOME="$TEST_HOME" "$KP_BIN" server start --bind ":$TEST_PORT" > "$LOG_FILE" 2>&1 &
  sleep 2
  if ! lsof -nP -iTCP:"$TEST_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "daemon failed to bind :$TEST_PORT — see $LOG_FILE" >&2
    tail -20 "$LOG_FILE" >&2 || true
    exit 1
  fi
  echo "ready: HOME=$TEST_HOME chat → make dev-models-chat"
  ;;

chat)
  ensure_binary
  if ! lsof -nP -iTCP:"$TEST_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "no daemon on :$TEST_PORT — run: make dev-models-server" >&2
    exit 1
  fi
  HOME="$TEST_HOME" KITTYPAW_API_URL="http://localhost:$TEST_PORT" \
    "$KP_BIN" chat --account default
  ;;

stop)
  ensure_binary
  HOME="$TEST_HOME" "$KP_BIN" server stop || true
  ;;

clean)
  if [[ "${1:-}" != "--yes" ]]; then
    echo "this removes $TEST_HOME and $LOG_FILE — re-run with: $0 clean --yes" >&2
    exit 1
  fi
  HOME="$TEST_HOME" "$KP_BIN" server stop 2>/dev/null || true
  rm -rf "$TEST_HOME" "$LOG_FILE"
  echo "removed $TEST_HOME and $LOG_FILE"
  ;;

status)
  echo "TEST_HOME=$TEST_HOME"
  echo "TEST_PORT=$TEST_PORT"
  echo "LOG_FILE=$LOG_FILE"
  if [[ -f "$TEST_HOME/accounts/default/config.toml" ]]; then
    echo "config: present"
  else
    echo "config: missing (run: make dev-models-setup)"
  fi
  if lsof -nP -iTCP:"$TEST_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
    echo "daemon: running on :$TEST_PORT"
  else
    echo "daemon: not running"
  fi
  for v in GROQ_API_KEY MISTRAL_API_KEY; do
    if [[ -n "${!v:-}" ]]; then
      echo "$v: set"
    else
      echo "$v: missing"
    fi
  done
  ;;

help|*)
  cat <<USAGE
$(basename "$0") — local /model demo harness

Usage:
  $0 setup [--force]   create isolated config (idempotent)
  $0 server            start daemon on :$TEST_PORT (HOME=$TEST_HOME)
  $0 chat              attach chat REPL
  $0 stop              stop daemon
  $0 clean --yes       remove TEST_HOME (explicit confirmation)
  $0 status            print state

Env:
  KITTYPAW_DEV_HOME    isolation home (default: /tmp/kittypaw-dev-models)
  KITTYPAW_DEV_PORT    daemon port    (default: 3001)
  GROQ_API_KEY         required for server
  MISTRAL_API_KEY      required for server

Typical flow (Makefile aliases shown):
  export GROQ_API_KEY=gsk_...
  export MISTRAL_API_KEY=...
  make dev-models-setup
  make dev-models-server
  make dev-models-chat        # in REPL: /model, /model mistral-medium, ...
  make dev-models-stop
USAGE
  ;;
esac
